name: nf_iseg_benchmark_tf
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - abseil-cpp=20210324.2=h9c3ff4c_0
  - absl-py=2.1.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.4.3=pyhd8ed1ab_0
  - aiohttp=3.10.5=py38h2019614_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_2
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - blinker=1.8.2=pyhd8ed1ab_0
  - brotli-python=1.1.0=py38h17151c0_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2024.12.14=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.5.0=pyhd8ed1ab_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py38heb5c249_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cryptography=39.0.0=py38h1724139_0
  - cuda-version=11.8=h70ddcb2_3
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cudnn=8.9.7.29=hbc23b4c_3
  - frozenlist=1.4.1=py38h01eb140_0
  - gast=0.5.5=pyhd8ed1ab_0
  - giflib=5.2.2=hd590300_0
  - google-auth=2.35.0=pyhff2d567_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyhd8ed1ab_1
  - grpc-cpp=1.45.2=h9d3bbbb_5
  - grpcio=1.45.0=py38ha0cdfde_0
  - h2=4.1.0=py38h578d9bd_0
  - h5py=3.9.0=nompi_py38h89e2d6c_100
  - hdf5=1.14.0=nompi_h5231ba7_103
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - jpeg=9e=h0b41bf4_3
  - keras=2.8.0=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=hf9c8cef_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libaec=1.1.3=h59595ed_0
  - libblas=3.9.0=20_linux64_openblas
  - libcblas=3.9.0=20_linux64_openblas
  - libcurl=7.87.0=h6312ad2_0
  - libedit=3.1.20240808=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - liblapack=3.9.0=20_linux64_openblas
  - liblzma=5.6.3=hb9d3cd8_1
  - liblzma-devel=5.6.3=hb9d3cd8_1
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libpng=1.6.43=h2797004_0
  - libprotobuf=3.20.3=h3eb15da_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=h4ab18f5_6
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.5=py38h01eb140_0
  - multidict=6.0.5=py38h01eb140_0
  - nccl=2.24.3.1=h03a54cd_0
  - ncurses=6.5=h2d0b736_2
  - numpy=1.24.4=py38h59b608b_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openssl=1.1.1w=hd590300_0
  - opt_einsum=3.4.0=pyhd8ed1ab_0
  - packaging=24.2=pyhd8ed1ab_2
  - pip=24.3.1=pyh8b19718_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - protobuf=3.20.3=py38h8dc9893_1
  - pyasn1=0.6.1=pyhd8ed1ab_1
  - pyasn1-modules=0.4.1=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pyjwt=2.9.0=pyhd8ed1ab_1
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.15=h257c98d_0_cpython
  - python-flatbuffers=24.3.25=pyh59ac667_0
  - python_abi=3.8=5_cp38
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - re2=2022.06.01=h27087fc_1
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - scipy=1.10.1=py38h59b608b_3
  - setuptools=75.3.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=hdb0a2a9_1
  - sqlite=3.46.0=h6d4b2fc_0
  - tensorboard=2.8.0=pyhd8ed1ab_1
  - tensorboard-data-server=0.6.1=py38h2b5fc30_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.8.1=cuda112py38hded6998_0
  - tensorflow-base=2.8.1=cuda112py38had2df90_0
  - tensorflow-estimator=2.8.1=cuda112py38hf5dcc89_0
  - tensorflow-gpu=2.8.1=cuda112py38h0bbbad9_0
  - termcolor=2.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - werkzeug=3.0.6=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - wrapt=1.16.0=py38h01eb140_0
  - xz=5.6.3=hbcc6ac9_1
  - xz-gpl-tools=5.6.3=hbcc6ac9_1
  - xz-tools=5.6.3=hb9d3cd8_1
  - yarl=1.9.4=py38h01eb140_0
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py38h62bed22_0
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - docopt==0.6.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - humanfriendly==10.0
      - imageio==2.35.1
      - importlib-resources==6.4.5
      - jsonpickle==4.0.1
      - lazy-loader==0.4
      - medpy==0.5.2
      - mpmath==1.3.0
      - munch==2.5.0
      - networkx==3.1
      - nibabel==5.2.1
      - onnx==1.17.0
      - onnxruntime==1.19.2
      - onnxruntime-gpu==1.19.2
      - opencv-python==4.11.0.86
      - pandas==2.0.3
      - pillow==10.4.0
      - py-cpuinfo==9.0.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pywavelets==1.4.1
      - scikit-image==0.21.0
      - simpleitk==2.4.1
      - smmap==5.0.2
      - sympy==1.13.3
      - tensorflow-addons==0.18.0
      - tf2onnx==1.16.1
      - tifffile==2023.7.10
      - tqdm==4.67.1
      - typeguard==4.4.0
      - tzdata==2024.2
